name: Build
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armv7-a, armv8-a]
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          sudo apt install make -y
          sudo apt install cmake -y
          sudo apt install automake -y
          sudo apt install autoconf -y
          sudo apt install libtool -y
          sudo apt install build-essential -y
          sudo apt install gcc-multilib -y
          sudo apt install dos2unix -y
          sudo apt install python -y
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH="$PATH:/home/runner/work/jsV8/jsV8/depot_tools"
          sudo chmod -R 777 *
          dos2unix build.sh
          cd depot_tools
          gclient
          fetch v8
          cd v8
          gclient sync
          ./build/install-build-deps.sh
      - name: Build
        run: ./build.sh ${{matrix.arch}}
      - uses: actions/upload-artifact@v2
        with:
          name: v8-${{matrix.arch}}
          path: depot_tools/v8/third_party/android_ndk/BUILD.gn
